export const FETCH_METEORITES = 'FETCH_METEORITES'
export const FETCH_METEORITES_ERROR = 'FETCH_METEORITES_ERROR';
export const FETCH_METEORITES_SUCCESS= 'FETCH_METEORITES_SUCCESS';
export const SEARCH_RESULTS= 'SEARCH_RESULTS';
